Order rooms by name in the schedule
openSUSE/osem pull request #2913
Opened 2022-01-24 00:16 UTC by AndrewKvalheim

### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [x] The tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate).
- [ ] I have added necessary documentation (if appropriate).

### Short description of what this resolves

On the published schedule, rooms are listed in undefined order—in practice, usually the order of creation. This can make the schedule confusing to read.

### Changes proposed in this pull request

An explicit ordering feature would be useful, but for now it’s an improvement to just order by name.

2022-01-31 13:38 UTC, hennevogel requested changes

2022-01-31 13:38 UTC, hennevogel commented on spec/features/schedules_spec.rb
> +  describe 'with unalphabetized rooms' do
I don't think we need a spec for `.order`. The `ActiveRecord` test suite will make sure that this will never break...

CI time is developer time.

2022-02-06 01:30 UTC, AndrewKvalheim commented
Makes sense, thanks.

2022-02-07 12:15 UTC, hennevogel approved these changes

2022-02-07 12:16 UTC, merged